🐛 Emacs 30.x でコケるのを回避する試み
(require 'forge) 時に以下のエラーが発生していた:

Error: Invalid escape char syntax: \x not followed by hex digit

rg --type elisp '\\x[^0-9a-fA-F] で依存パッケージ内を検索したところ、
yaml.el が引っかかり、 https://github.com/zkry/yaml.el/pull/46 というのがあった。

なので、これで修正されるのではないかと考え、 yaml.el を最新化する。